# Eigenvectors And Eigenvalues

## Linear Transformation

In [1]:
import numpy as np

A = np.array([[2, 1], 
              [1, 3]])
v = np.array([1, 2])
transformed_vect = A @ v

print("Original vector:", v)
print("\nTransformed vector:", transformed_vect)


Original vector: [1 2]

Transformed vector: [4 7]


## Eigenvectors and Eigenvalues Computation

### `np.linalg.eig(A)` computes the eigenvalues and eigenvectors of matrix A.

In [2]:
A = np.array([[4, -2], 
              [1,  1]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues:
 [3. 2.]

Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## Eigendecomposition

### Reconstructing A Using Q * Λ * Q⁻¹ 

In [3]:
A = np.array([[4, -2], 
              [1,  1]])

eigenvalues, eigenvectors = np.linalg.eig(A)
Q = eigenvectors  # Eigenvectors matrix
Λ = np.diag(eigenvalues)  # Diagonal matrix of eigenvalues
A_reconstructed = Q @ Λ @ np.linalg.inv(Q)  # Reconstruct A

print("Original Matrix:\n", A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)
print("\nReconstructed Matrix:\n", A_reconstructed)


Original Matrix:
 [[ 4 -2]
 [ 1  1]]

Eigenvalues:
 [3. 2.]

Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

Reconstructed Matrix:
 [[ 4. -2.]
 [ 1.  1.]]
